name: "conda-publish"
description: "Build and publish Conda package to Anaconda"
author: "paulscherrerinstitute"
branding:
  icon: "package"
  color: "purple"
inputs:
  subdir:
    description: "Sub-directory with conda recipe"
    required: true
    default: "conda-recipe"
  anacondatoken:
    description: "Anaconda access token"
    required: true
  channel_opts:
    description: "Channel options"
    required: true
    default: ""
  packagename:
    description: "Package name"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
